### ISSUE TITLE
Strength and Rad interaction

### ISSUE THREAD

**Issue by KendallHarter** [siggame/MegaMinerAI-14#13]
How do these things interact?
How does something gain strength vs. rads increasing strength?
Also need to work out formulas for these. [Based on how the interactions works, so linear?]
Also what is the purpose of the min strength? How does a plant lose strength?

**Comment by Tarnasa** [comment]
My thinking...
Start with a linear relationship:
strength = minStrength + (maxStrength - minStrength) \* (rads / maxRads)
Then make buffs from soakers add to the rads of a plant? (And make sure they don't go over max)
strength = minStrength + (maxStrength - minStrength) \* min((rads + buff) / maxRads, 1.0)

**Comment by KendallHarter** [comment]
``` python
damage = strength + int(strength * multiplier * (rads / maxRads + constant))
```

constant may be < 0
