### ISSUE TITLE
Debuff for Titan

### ISSUE THREAD

**Issue by Tarnasa** [siggame/MegaMinerAI-14#24]
When a plant is in the range of an enemy Titan, its base-strength should decrease

**Comment by KendallHarter** [comment]
I believe that the idea was that attacking with the titan would cause a decrease in strength, not base strength.
[Decreasing base strength wouldn't do much anyways.]

**Comment by Tarnasa** [comment]
Plants will automatically be debuffed when in range of an enemy Titan
