### ISSUE TITLE
New global, damage taken from standing in pool

### ISSUE THREAD

**Issue by Tarnasa** [siggame/MegaMinerAI-14#31]

**Comment by Tarnasa** [comment]
OR this could come from a variable of the pool

**Comment by Tarnasa** [comment]
This will come from a new global variable

**Comment by TheGag96** [comment]
What do you mean by "global variable"? Wouldn't this be tracked by each individual plant?

**Comment by Tarnasa** [comment]
For now, it will be the same for all plants.  And by global variable I mean that there will be function for the clients to get this value, (something like getMapWidth)
