### ISSUE TITLE
How far can a bumbleweed move in a turn?

### ISSUE THREAD

**Issue by Tarnasa** [siggame/MegaMinerAI-14#32]
Currently it can move anywhere from anywhere in a turn.
Which variable would we use to limit this?
range is already the range at which this unit can radiate (heal) other plants

**Comment by TheGag96** [comment]
We could have one called "mobility". That name seems fine.

**Comment by KendallHarter** [comment]
Create a variable in the config because it is the only unit to which it would apply.

**Comment by Tarnasa** [comment]
Will make global variable
