### ISSUE TITLE
Qmake not generating makefile for visualizer

### ISSUE THREAD

**Issue by Loran425** [siggame/MegaMinerAI-14#51]
Following the instruction for the cppvis works up until you try `qmake` in the MegaMinerAI-14 clone folder.

**Comment by BryceMehring** [comment]
First make sure you ran `CreateVisualizerSymbolicLinks.sh` on the root of the repo. Directory structure for script to work:

```
MegaMinerAI-14/
cppVis/
```

You need to use `qmake-qt4` instead of `qmake` within `visualizer/` to build the visualizer.

**Comment by Loran425** [comment]
Ok that fixed it.
Had all the links correct just didn't know to be in the `visualizer/` folder.
Rereading the wiki it says to be in the root so `MegaMinerAI-14/`
Updating the cppVis wiki to reflect you suggestion.
