### ISSUE TITLE
Set up IRC

### ISSUE THREAD

**Issue by michaelwisely** [siggame/MegaMinerAI-14#52]
Create a room on freenode.net or a similar service. #mmai14

**Comment by Tarnasa** [comment]
What is the server address?

**Comment by jonsimington** [comment]
server: irc.freenode.net
channel: #megaminer

**Comment by jonsimington** [comment]
you can connect using http://webchat.freenode.net/

make sure to register your nickname using `/msg nickserv register <password> <your email address>`.

once your nickname is registered, we can give you operator status, which allows you to have some special privileges.

**Comment by michaelwisely** [comment]
Sounds done to me!
