### ISSUE TITLE
Temp accounts

### ISSUE THREAD

**Issue by michaelwisely** [siggame/MegaMinerAI-14#53]
Ask IT for temporary logins for competitors to use. We asked for 50 logins for Droids, but that might not be necessary. Each team only gets one login, so we might be able to get away with ~20. What do you think @russleyshaw, @jonsimington? How many temp accounts were used last semester?

Also, find out what IT needs from out-of-town competitors who want to register their devices with the network. 

We need these soon.

**Comment by Tarnasa** [comment]
I have put in the request for 50 temp loggins

**Comment by jonsimington** [comment]
We had soooo many temp accounts left over. I think around 20 or so MAX were used. We should be safe with ~50. 

—
