### ISSUE TITLE
Sever error

### ISSUE THREAD

**Issue by brandonphelps** [siggame/MegaMinerAI-14#55]
I am getting an error
AttributeError: 'Match' object has no attribute 'logJson' at server/game_app/match.py line 30

Ideas? It looks like this has something to do with game logs not getting printed maybe? 

This occurs when a client tries to connect to the server, the client is given Cannot join game 1:

**Comment by Tarnasa** [comment]
Are sure that you are starting the server from within the server/ folder?
This happens to me when I run python server/main.py from the above folder

**Comment by brandonphelps** [comment]
hmm yeah I think i might be running python server/main.py, can you explain why that matters?

**Comment by brandonphelps** [comment]
Running python server/main.py doesn't seem to affect whether clients can connect or not, I am still getting the same error.

**Comment by BryceMehring** [comment]
@brandonphelps, is there anything requiring you to run the server via `python server/main.py`?
