### ISSUE TITLE
No Uproots

### ISSUE THREAD

**Issue by TotalBollocks** [siggame/MegaMinerAI-14#77]
Soakers and Spawners are starting with 0 uprootsLeft

**Comment by Tarnasa** [comment]
This is intentional for the spawner.  For the soaker, I'm OK with it either way.  Though having more units that can't move seems more interesting to me

**Comment by TotalBollocks** [comment]
I think the soakers should be able to move to allow them to buff in units at a strategic location and time. This also prevents them from becoming useless once the pool they spawned in is drained. Moving them to a new pool seems important.

**Comment by Tarnasa** [comment]
True, but then that kinda of removes the bonus of positioning your forces near pools.

**Comment by Tarnasa** [comment]
Actually I like your idea, lets do it

**Comment by Tarnasa** [comment]
Actually no, soaker no move
