### ISSUE TITLE
Check winner

### ISSUE THREAD

**Issue by jjherman94** [siggame/MegaMinerAI-14#8]
The check winner function needs to be made. Assigning myself

**Comment by jjherman94** [comment]
I made the function on my fork, but I have no clue how to push it to the main thing. And it won't let me pull from the main thing anymore because of merge conflicts.

**Comment by Tarnasa** [comment]
![img](https://help.github.com/assets/images/help/pull_requests/pull-request-start-review-button.png)
On the github page for your forked version of the repo.
